version: '2'

networks:
  punisher:
    external: true

services:
  punisher-db:
    image: percona:5.7
    restart: always
    volumes:
      - ./configs/mysql/dump:/docker-entrypoint-initdb.d
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - punisher

  punisher:
    image: hub.maddevs.co/punisher
    restart: always
    environment:
      - MENTORS_CHAT=${BOT_MENTORS_CHAT}
      - NOTIFY_MENTORS=${BOT_NOTIFY_MENTORS}
      - PUNISHMENT_TYPE=${BOT_PUNISHMENT_TYPE}
      - INTERNS_CHAT_ID=${BOT_INTERNS_CHAT_ID}
      - PUNISH_TIME=${BOT_PUNISH_TIME}
      - DATABASE_URL=${BOT_DATABASE_URL}
      - TELEGRAM_TOKEN=${BOT_TELEGRAM_TOKEN}
    networks:
      - punisher
